tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "osx-cross/avr"
tap "px4/px4"
tap "heroku/brew"

brew "mas"
brew "git"

cask "atom"
cask "visual-studio-code"
cask "iterm2"
cask "1password"
cask "macdown"
cask "google-chrome"
cask "firefox"
cask "spectacle"
cask "slack"
cask "virtualbox"
cask "transmission"
cask "vlc"
cask "spotify"
cask "telegram"
cask "github"
cask "calibre"
cask "appcleaner"
cask "figma"
cask "notion"
cask "zoomus"

brew "neovim"
brew "nvm"
brew "yarn"
brew "rbenv"
brew "ruby-build"
brew "imagemagick"
brew "libpng"
brew "watchman"
brew "heroku/brew/heroku"
brew "mysql"
brew "postgresql"
brew "redis"
brew "mongodb"

brew "wifi-password"
brew "youtube-dl"
brew "jq"

brew "avrdude"
brew "dfu-programmer"
brew "osx-cross/avr/avr-gcc"
brew "px4/px4/gcc-arm-none-eabi"

mas "Things3", id: 904280696
mas "Xcode", id: 497799835
