tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "schollz/tap"

brew "mas"
brew "git"
brew "watchman"
brew "jq"
brew "wifi-password"
brew "youtube-dl"
brew "croc"

cask "1password"
cask "telegram"
cask "slack"
cask "figma"
cask "notion"
cask "iterm2"
cask "github"
cask "blender"
cask "visual-studio-code"
cask "microsoft-edge-dev"
cask "safari-technology-preview"
cask "google-chrome"
cask "firefox"
cask "virtualbox"
cask "docker"
cask "cyberduck"
cask "vlc"
cask "calibre"
cask "spotify"
cask "transmission"
cask "appcleaner"
cask "spectacle"

mas "Things3", id: 904280696
mas "Xcode", id: 497799835
